/**
 *
 * $Id$
 */
package StateMachine.validation;

import StateMachine.State;

/**
 * A sample validator interface for {@link StateMachine.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
	boolean validate();

	boolean validateAction(String value);
	boolean validateTrigger(String value);
	boolean validateSource(State value);
	boolean validateTarget(State value);
	boolean validateId(int value);
	boolean validateName(String value);
}
