/**
 *
 * $Id$
 */
package StateMachine.validation;

import StateMachine.State;
import StateMachine.Transition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link StateMachine.WashingMachine}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WashingMachineValidator {
	boolean validate();

	boolean validateStates(EList<State> value);
	boolean validateTransitions(EList<Transition> value);
}
